<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <Version>1.0.0</Version>
  </PropertyGroup>

<PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <SelfContained>true</SelfContained>
    <PublishAot>false</PublishAot>
    <CetCompat>false</CetCompat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pos.Local\Pos.Local.csproj" />
    <ProjectReference Include="..\Pos.Application\Pos.Application.csproj" />
    <ProjectReference Include="..\Pos.Contracts\Pos.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="System.IO.Packaging" />

  </ItemGroup>

</Project>