<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.Local\Pos.Local.csproj" />
    <ProjectReference Include="..\Pos.Application\Pos.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.ReactiveUI" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="ClosedXML" />
     <PackageVersion Include="QuestPDF" Version="2024.3.0" />
    
    <PackageVersion Include="System.IO.Packaging" Version="8.0.0" />

  </ItemGroup>

</Project> 