<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pos.Contracts\Pos.Contracts.csproj" />
    <ProjectReference Include="..\Pos.Domain\Pos.Domain.csproj" />
    <ProjectReference Include="..\Pos.Application\Pos.Application.csproj" />
    <ProjectReference Include="..\Pos.Infrastructure\Pos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
