<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
  
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <SelfContained>true</SelfContained>
    <PublishAot>false</PublishAot>
    <CetCompat>false</CetCompat>
  </PropertyGroup>
    <ProjectReference Include="..\Pos.Server\Pos.Server.csproj" />
    <ProjectReference Include="..\Pos.Contracts\Pos.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
</Project>
